### ISSUE TITLE
Rich Responses (Account Linking)

### ISSUE THREAD

**Issue by awais786327** [actions-on-google/assistant-conversation-nodejs#16]
Support for rich responses? like card, carousal, ssml, SimpleResponse etc

**Comment by awais786327** [comment]
and most imp Account Linking?

**Comment by taycaldwell** [comment]
You can read more about sending rich responses here: https://developers.google.com/assistant/conversational/prompts-rich

Account linking details can be found [here](https://developers.google.com/assistant/identity/google-sign-in).

**Comment by awais786327** [comment]
Sending audio responses like SSML and SimpleResponses?
