### ISSUE TITLE
No Documentation for Permissions / Device Location

### ISSUE THREAD

**Issue by ChrisSofokleous** [actions-on-google/assistant-conversation-nodejs#29]
No up to date documentation exists equivalent to the documentation on helper intents around 'actions.intent.PERMISSION'

Found here: https://developers.google.com/assistant/conversational/df-asdk/helpers

**Comment by sascha-schieferdecker** [comment]
I second that. Dug through a lot of pages, found nothing...

**Comment by Fleker** [comment]
Location is available in v3.6.0 (0e314453b91cf3a26795db6c847dbf899201a258). Permissions are now available in the [developer documentation](https://developers.google.com/assistant/conversational/permissions).
