### ISSUE TITLE
missing the 'index' type in MediaContext interface

### ISSUE THREAD

**Issue by panaC** [actions-on-google/assistant-conversation-nodejs#30]
https://github.com/actions-on-google/assistant-conversation-nodejs/blob/402f7d113c5c561c0850ad8aabdcf9643a509a22/src/api/schema.ts#L96-L102

`context: Context { media: { index: 0, progress: '6.733s' } },`

**Comment by Fleker** [comment]
Thanks for reporting. There seem to be a few types/interfaces missing. We'll be regenerating the schema soon.
