### ISSUE TITLE
Exit/Close conversation from Webhook

### ISSUE THREAD

**Issue by cbothra** [actions-on-google/assistant-conversation-nodejs#36]
Hi,

I am building an action and using webhook. There is a use case in the intent handler when after giving prompt to user I would like to close the conversation from webhook itself. I went through the @assistant/conversation api documentation but couldn't find any way to do that.

Any help?

Thanks-in-advance

**Comment by Fleker** [comment]
You can use [scene transitions](https://developers.google.com/assistant/conversational/webhooks?tool=builder#transition_scenes) to transition to the built-in scene `actions.scene.END_CONVERSATION`.

**Comment by cbothra** [comment]
Hi @Fleker, Thanks and I confirm that this works as intended.
