### ISSUE TITLE
Forced to make intents global when used as custom intents in scenes

### ISSUE THREAD

**Issue by actionsoneverything** [actions-on-google/assistant-conversation-nodejs#44]
I'm currently migrating from Dialogflow to Actions Builder, things have gone well so far however after added custom intents to my scenes the test simulator prompts me with the warning "Intent 'intent_name' is used as an action, but not added as a global event." blocking my ability to test the action until I configure the intent as global.

Since configuring intents as global enables implicit invocation it seems inappropriate to apply it to all intents, especially those which have no business being accessed implicitly.

Has anyone experienced this warning? Any tips to get past this error without configuring the intent as global?

Cheers

**Comment by Fleker** [comment]
Let's consolidate answers to the [StackOverflow post](https://stackoverflow.com/questions/69086458/forced-to-make-intents-global-when-used-as-custom-intents-in-scenes).
