### ISSUE TITLE
Test Simulator fails to load latest Actions Builder changes

### ISSUE THREAD

**Issue by actionsoneverything** [actions-on-google/assistant-conversation-nodejs#9]
I'm working on migrating from Dialogflow to Actions Builder, things have been going well however since yesterday I've been unable to load the latest Actions Builder changes in the Test Simulator, blocking my ability to test/develop my action.

I'm getting the following errors in the web console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
Failed to load resource: the server responded with a status of 504 () /m/actions/agents/draft/createlocalizeduserpreview:1
Failed to load resource: the server responded with a status of 401 () GetPeople:1
```

![image](https://user-images.githubusercontent.com/54109773/94251818-00275900-ff1b-11ea-9ad5-17ad3bd4c92e.png)

The 'updating preview' spinning loader shows for about 2.5 mins before this error shows.

There are no errors/warnings reported in the develop tab.

How do I proceed with this issue?

Thanks

**Comment by 7laria** [comment]
sometimes it takes more than a few minutes before the changes are available in the testing simulator. Just wait until the NLU training finish and then retry

**Comment by actionsoneverything** [comment]
Emailed AOG support, after a while this resolved itself.
